//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food4Life.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutPage
    {
        public int id { get; set; }
        public string article_text { get; set; }
    }
}
